#!/usr/bin/env python3
import os.path, sys, shutil

curr_path = "/home/usuisot/replace-script/"
if len(sys.argv) == 4:

    path = sys.argv[1]
    oldpattern = sys.argv[2]
    newpattern = sys.argv[3]


    print(newpattern)

    '''
    if os.path.exists(curr_path + path) == True:



    else:
        print("The path doesn't exist.\nCheck the README.md, if you don't know the correct syntax.")
    '''

else:
    print("This is invalid syntax.\nCheck the README.md, if you don't know")
