#!/usr/bin/env python3
import os.path, sys, shutil

subcommand = sys.argv[1]
path = '/home/usuisot/replace-script/test/edu/bvu/cs'

if subcommand == 'setup':
    if os.path.exists('/home/usuisot/replace-script/test') == True:
        shutil.rmtree('/home/usuisot/replace-script/test')
    os.makedirs(path)
    f1 = open(path+"/DevOps.java","w")
    f1.write("yup")
    f1.close()
    f2 = open(path+"/DevOpsMain.java","w")
    f2.write("sup")
    f2.close()


elif subcommand == 'teardown':
    if os.path.exists('/home/usuisot/replace-script/test') == True:
        shutil.rmtree('/home/usuisot/replace-script/test')
    else:
        print("You don't have a test file")

else:
    print("You have to use the correct script syntax.\nCheck the README.md if you don't know the correct syntax.")
